

# Authorized: next(), range(), len(), print(), import typing,
# typing.Generator, import random, random.*

# This exercise requires the use of generators with the yield keyword to create data streams
# on the fly. You must implement generator functions that produce values on-demand
# rather than storing everything in memory.
# ! Create an endless generator function gen_event() that picks a random name from a list
# ! of players, and a random action from a list of actions. Each time next() is called on this
# ! generator, it returns a new event as a tuple (name, action).
# From the main part of your script, loop a thousand times and display all 1000 events you
# get from your gen_event() .
# Then create a list of ten tuples generated by gen_event() again.
# Finally, create a new generator function consume_event that takes the previously created
# list, randomly pick one of its elements, remove it from the list, and yields it, until the list
# is empty. This generator must be used directly in the for .. in .. construct.

from typing import Generator
import random


def gen_event(names: list[str], actions: list[str]) -> Generator[tuple[str, str], None, None]:
    while True:
        r_n = random.choice(names)
        r_a = random.choice(actions)
        yield (r_n, r_a)


def consume_event(events: list[tuple[str, str]]) -> Generator[tuple[str, str], None, None]:
    while events:
        idx = random.randrange(len(events))
        yield events.pop(idx)


if __name__ == "__main__":
    print("=== Game Data Stream Processor ===")
    names: list[str] = ["Alice", "Bob", "Charlie", "Dylan", "Eve", "Fi", "Geb"]
    actions: list[str] = ["run", "eat", "sleep", "grab", "move", "climb", "swim", "release", "use"]
    limit = 10
    i = 0
    event_gen: Generator[tuple[str, str], None, None] = gen_event(names, actions)

    for i in range(1000):
        player, action = next(event_gen)
        print(f"Event {i}: Player {player} did action {action}")
        i += 1

    ten_tuples: list[tuple[str, str]] = []

    for i in range(10):
        ten_tuples.append(next(event_gen))

    print(f"Built list of 10 events: {ten_tuples}")
    event_consume: Generator[tuple[str, str], None, None] = consume_event(ten_tuples)
    for i in range(10):
        event = next(event_consume)
        print(f"Got event from list {event}")
        print(f"Remains in list: {ten_tuples}")
